### ISSUE TITLE
Use Result instead of specific class

### ISSUE THREAD

**Issue by luiz** [caelum/vraptor-freemarker#1]
Currently, to use Freemarker as the template engine, one must require the Freemarker class in the constructor and use its methods to include variables in the scope of the template.

It would be better if one could use the VRaptor's Result instead, keeping the standard of the framework and easing a possible template engine change. The final result could be something like this:

```
result.include("anObject", anObject);
result.use(Freemarker.class).of("path/to/template")
```

**Comment by guilhermesilveira** [comment]
Just dont forget to support both ways... We use freemarker to render other
things that are not http results.

Guilherme Silveira
On Sep 13, 2011 12:57 PM, "Luiz Fernando O. C. Real" <
reply@reply.github.com>
wrote:
